import React from 'react';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
} from 'chart.js';
import { Line } from 'react-chartjs-2';
import { useAppStore } from '../store/useAppStore';
import { Activity, TrendingUp, FileText, Check } from 'lucide-react';
import { useState } from 'react';

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend
);

export const MetricsPanel: React.FC = () => {
  const [reportCopied, setReportCopied] = useState(false);
  const { 
    epoch, trainLoss, testLoss, trainAccuracy, testAccuracy,
    datasetType, noise, trainTestSplit, sampleCount,
    hiddenLayers, activation, learningRate, regularization
  } = useAppStore();

  const generateReport = () => {
    const lastTrainAcc = (trainAccuracy[trainAccuracy.length - 1] * 100 || 0).toFixed(2);
    const lastTestAcc = (testAccuracy[testAccuracy.length - 1] * 100 || 0).toFixed(2);
    const lastTrainLossVal = (trainLoss[trainLoss.length - 1] || 0).toFixed(4);
    const lastTestLossVal = (testLoss[testLoss.length - 1] || 0).toFixed(4);

    const report = `
# Tensor canvas Training Report

## Hyperparameters
- **Dataset:** ${datasetType}
- **Noise:** ${noise}
- **Train/Test Split:** ${trainTestSplit * 100}%
- **Sample Count:** ${sampleCount}
- **Architecture:** ${hiddenLayers.join(' → ')}
- **Activation:** ${activation}
- **Learning Rate:** ${learningRate}
- **Regularization:** ${regularization}

## Final Metrics (Epoch ${epoch})
- **Training Accuracy:** ${lastTrainAcc}%
- **Testing Accuracy:** ${lastTestAcc}%
- **Training Loss:** ${lastTrainLossVal}
- **Testing Loss:** ${lastTestLossVal}

---
*Generated by [Tensor canvas](${window.location.href})*
    `.trim();

    navigator.clipboard.writeText(report);
    setReportCopied(true);
    setTimeout(() => setReportCopied(false), 2000);
  };

  const lossData = {
    labels: Array.from({ length: trainLoss.length }, (_, i) => i + 1),
    datasets: [
      {
        label: 'Train Loss',
        data: trainLoss,
        borderColor: '#3b82f6',
        backgroundColor: 'rgba(59, 130, 246, 0.5)',
        tension: 0.4,
        pointRadius: 0,
      },
      {
        label: 'Test Loss',
        data: testLoss,
        borderColor: '#f97316',
        backgroundColor: 'rgba(249, 115, 22, 0.5)',
        tension: 0.4,
        pointRadius: 0,
      },
    ],
  };

  const accData = {
    labels: Array.from({ length: trainAccuracy.length }, (_, i) => i + 1),
    datasets: [
      {
        label: 'Train Acc',
        data: trainAccuracy,
        borderColor: '#10b981',
        backgroundColor: 'rgba(16, 185, 129, 0.5)',
        tension: 0.4,
        pointRadius: 0,
      },
      {
        label: 'Test Acc',
        data: testAccuracy,
        borderColor: '#8b5cf6',
        backgroundColor: 'rgba(139, 92, 246, 0.5)',
        tension: 0.4,
        pointRadius: 0,
      },
    ],
  };

  const options = {
    responsive: true,
    maintainAspectRatio: false,
    plugins: {
      legend: {
        display: false,
      },
    },
    scales: {
      x: { display: false },
      y: {
        grid: { color: 'rgba(150, 150, 150, 0.1)' },
        ticks: { font: { size: 10 } },
      },
    },
  };

  const lastTrainLoss = trainLoss[trainLoss.length - 1] || 0;
  const lastTestLoss = testLoss[testLoss.length - 1] || 0;
  const isOverfitting = lastTestLoss > lastTrainLoss * 1.5 && epoch > 50;

  return (
    <div className="flex flex-col gap-6 p-6 h-full bg-white dark:bg-zinc-900 border-l border-zinc-200 dark:border-zinc-800 overflow-y-auto">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2 text-zinc-900 dark:text-zinc-100 font-semibold">
          <Activity size={18} />
          <h2>Metrics</h2>
        </div>
        <div className="px-2 py-1 bg-zinc-100 dark:bg-zinc-800 rounded text-xs font-mono">
          Epoch: {epoch}
        </div>
      </div>

      <div className="space-y-6">
        <div className="space-y-2">
          <div className="flex justify-between items-center">
            <h3 className="text-xs font-medium text-zinc-500 uppercase tracking-wider">Loss</h3>
            <span className="text-xs font-mono text-blue-500">{lastTrainLoss.toFixed(4)}</span>
          </div>
          <div className="h-40">
            <Line data={lossData} options={options} />
          </div>
        </div>

        <div className="space-y-2">
          <div className="flex justify-between items-center">
            <h3 className="text-xs font-medium text-zinc-500 uppercase tracking-wider">Accuracy</h3>
            <span className="text-xs font-mono text-emerald-500">{(trainAccuracy[trainAccuracy.length - 1] * 100 || 0).toFixed(1)}%</span>
          </div>
          <div className="h-40">
            <Line data={accData} options={options} />
          </div>
        </div>

        {isOverfitting && (
          <div className="p-3 bg-amber-50 dark:bg-amber-900/20 border border-amber-200 dark:border-amber-800 rounded-lg flex items-start gap-2">
            <TrendingUp size={16} className="text-amber-500 mt-0.5" />
            <div>
              <p className="text-xs font-semibold text-amber-700 dark:text-amber-400">Potential Overfitting</p>
              <p className="text-[10px] text-amber-600 dark:text-amber-500">Test loss is significantly higher than training loss.</p>
            </div>
          </div>
        )}

        <button 
          onClick={generateReport}
          className="w-full flex items-center justify-center gap-2 px-4 py-3 bg-zinc-100 dark:bg-zinc-800 hover:bg-zinc-200 dark:hover:bg-zinc-700 rounded-xl transition-all text-sm font-semibold text-zinc-700 dark:text-zinc-300 border border-zinc-200 dark:border-zinc-700"
        >
          {reportCopied ? <Check size={16} className="text-emerald-500" /> : <FileText size={16} />}
          {reportCopied ? 'Report Copied!' : 'Generate MD Report'}
        </button>
      </div>
    </div>
  );
};
